const locationOptions = [
  { label: "Cairo", value: "CAIRO" },
  { label: "Giza", value: "GIZA" },
  { label: "Alexandria", value: "ALEXANDRIA" },
  { label: "Aswan", value: "ASWAN" },
  { label: "Luxor", value: "LUXOR" },
  { label: "Qalyubia", value: "AL_QALYUBIYA" },
  { label: "Sharqia", value: "EASTERN" },
  { label: "Gharbia", value: "GHARBIA" },
  { label: "Faiyum", value: "FAIYUM" },
  { label: "Beni Suef", value: "BANI_SWEIF" },
  { label: "Minya", value: "AL_MINYA" },
  { label: "Assiut", value: "ASYUT" },
  { label: "Sohag", value: "SUHAJ" },
  { label: "Qena", value: "QENA" },
  { label: "Red Sea", value: "RED_SEA" },
  { label: "South Sinai", value: "SOUTH_SINAI" },
  { label: "North Sinai", value: "NORTH_SINAI" },
  { label: "New Valley", value: "NEW_VALLEY" },
  { label: "Damietta", value: "DAMIETTA" },
  { label: "Dakahlia", value: "AD_DAKAHLIYA" },
  { label: "Port Said", value: "PORT_SAID" },
  { label: "Suez", value: "SUEZ" },
  { label: "Ismailia", value: "AL_ISMAILIYA" },
  { label: "Menoufia", value: "AL_MINUFIYA" },
  { label: "Kafr El Sheikh", value: "KAFR_EL_SHEIKH" },
  { label: "Beheira", value: "THE_LAKE" },
  { label: "Matrouh", value: "MATRUH" },
];
const locationOptionsAr = [
  { label: "القاهرة", value: "CAIRO" },
  { label: "الجيزة", value: "GIZA" },
  { label: "الإسكندرية", value: "ALEXANDRIA" },
  { label: "أسوان", value: "ASWAN" },
  { label: "الأقصر", value: "LUXOR" },
  { label: "القليوبية", value: "AL_QALYUBIYA" },
  { label: "الشرقية", value: "EASTERN" },
  { label: "الغربية", value: "GHARBIA" },
  { label: "الفيوم", value: "FAIYUM" },
  { label: "بني سويف", value: "BANI_SWEIF" },
  { label: "المنيا", value: "AL_MINYA" },
  { label: "أسيوط", value: "ASYUT" },
  { label: "سوهاج", value: "SUHAJ" },
  { label: "قنا", value: "QENA" },
  { label: "البحر الأحمر", value: "RED_SEA" },
  { label: "جنوب سيناء", value: "SOUTH_SINAI" },
  { label: "شمال سيناء", value: "NORTH_SINAI" },
  { label: "الوادي الجديد", value: "NEW_VALLEY" },
  { label: "دمياط", value: "DAMIETTA" },
  { label: "الدقهلية", value: "AD_DAKAHLIYA" },
  { label: "بورسعيد", value: "PORT_SAID" },
  { label: "السويس", value: "SUEZ" },
  { label: "الإسماعيلية", value: "AL_ISMAILIYA" },
  { label: "المنوفية", value: "AL_MINUFIYA" },
  { label: "كفر الشيخ", value: "KAFR_EL_SHEIKH" },
  { label: "البحيرة", value: "THE_LAKE" },
  { label: "مطروح", value: "MATRUH" },
];
export  {locationOptions , locationOptionsAr};
